apps/auction_web/lib/auction_web/router.ex
defmodule AuctionWeb.Router do
  use AuctionWeb, :router

  """
  Every request that goes through the / top-level route is piped through this browser
  pipeline. We need to fetch the session before we try to access it in our plug (with
  Plug.Conn.get_session/2), so perhaps the best place to put the authenticator is at
  the end of the browser pipeline.
  """

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug AuctionWeb.Authenticator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AuctionWeb do
    pipe_through :browser

    get "/closed", ItemController, :closed, as: :closed

    resources "/items", ItemController, only: [:index, :new, :create, :show, :edit, :update] do
      resources "/bids", BidController, only: [:create]
    end

    resources "/users", UserController, only: [:show, :new, :create]

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", AuctionWeb.Api do
    pipe_through :api

    """
    already have an AuctionWeb.ItemController that handles HTML requests, but
    now you’ll introduce a AuctionWeb.Api.ItemController to handle JSON requests.
    The namespacing keeps them separate and communicates their purpose.
    """

    resources "/items", ItemController, only: [:index, :show]
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: AuctionWeb.Telemetry
    end
  end
end

apps/auction_web/lib/auction_web/controllers/api/item_controller.ex
defmodule AuctionWeb.Api.ItemController do
  use AuctionWeb, :controller

  def index(conn, _params) do
    items = Auction.list_items()
    render(conn, "index.json", items: items)
  end

  def show(conn, %{"id" => id}) do
    item = Auction.get_item_with_bids(id)
    render(conn, "show.json", item: item)
  end
end

apps/auction_web/lib/auction_web/controllers/item_controller.ex
defmodule AuctionWeb.ItemController do
  use AuctionWeb, :controller

  plug :require_logged_in_user when action in [:new]

  def index(conn, _params) do
    items = Auction.list_active_items()
    render(conn, "index.html", items: items)
  end

  def closed(conn, _params) do
    items = Auction.list_expired_items()
    render(conn, "closed.html", items: items)
  end

  def show(conn, %{"id" => id}) do
    item = Auction.get_item_with_bids(id)
    owner = Auction.get_user(item.user_id)
    empty_bid_struct = Auction.new_bid()
    render(conn, "show.html", item: item, bid: empty_bid_struct, owner: owner.username)
  end

  @doc """
  display page with form to create new item
  """
  def new(conn, _params) do
    item_changeset = Auction.new_item()
    render(conn, "new.html", item: item_changeset)
  end

  @doc """
  handle POST request from form to create new item
  """
  def create(conn, %{"item" => item_params}) do
    current_user = Map.get(conn.assigns, :current_user)

    case Auction.insert_item(item_params, current_user) do
      {:ok, item} -> redirect(conn, to: Routes.item_path(conn, :show, item))
      {:error, changeset} -> render(conn, "new.html", item: changeset)
    end

    # If the Auction.Item.changeset/2 function determines that the changeset is invalid,
    # Auction.insert_item/1 will return {:error, item}, with item being the changeset
    # with an errors attribute. In the case of an invalid item, you want to rerender the form
    # and notify the user of any errors so they can fix them. You need to make changes in
    # two places: AuctionWeb.ItemController.create/2 and .../templates/item/new
    # .html.eex. In the former, you need to handle the error case and render the form
    # again. In the latter, you need to display any relevant errors.
  end

  @doc """
  display page with form to edit item
  """
  def edit(conn, %{"id" => id}) do
    item_changeset = Auction.edit_item(id)
    render(conn, "edit.html", item: item_changeset)
  end

  @doc """
  update/2 will be remarkably similar to create/2—you need the params from the
  item’s form, but this time you also need the ID of the item to update. You’ll also pat-
  tern-match on the success or failure of the submission, so you know where to send
  your user next. Finally, you’ll also use Auction.update_item/2 instead of Auction
  .create_item/1.
  """
  def update(conn, %{"id" => id, "item" => item_params}) do
    item = Auction.get_item(id)

    case Auction.update_item(item, item_params) do
      {:ok, item} -> redirect(conn, to: Routes.item_path(conn, :show, item))
      {:error, item} -> render(conn, "edit.html", item: item)
    end
  end

  defp require_logged_in_user(%{assigns: %{current_user: nil}} = conn, _opts) do
    conn
    |> put_flash(:error, "Must be logged in to create an item!")
    |> redirect(to: Routes.item_path(conn, :index))
    |> halt()
  end

  defp require_logged_in_user(conn, _opts) do
    conn
  end
end

apps/auction_web/lib/auction_web/views/item_view.ex
defmodule AuctionWeb.ItemView do
  use AuctionWeb, :view
end

apps/auction_web/lib/auction_web/templates/item/closed.html.eex
<h2>Closed Auctions </h2>

<ul>
<%= for item <- @items do %>
<li>
<strong><%= link(item.title, to: Routes.item_path(@conn, :show, item)) %> </strong>: <%= item.description %>

</li>
<% end %>
</ul>

apps/auction_web/lib/auction_web/templates/item/edit.html.eex
<h1> Edit <%= @item.data.title %> </h1>

<%# remember, @item is a changeset, not an Auction.Item struct. The attributes of the underlying record of the
changeset can be accessed through the data attribute of the changeset. %>

<%= render("form.html", item: @item, action: Routes.item_path(@conn, :update, @item.data)) %>

apps/auction_web/lib/auction_web/templates/item/form.html.eex
<%= form_for @item, @action, fn f -> %>
<%= if @item.action do %>
	<div class="alert alert-danger">
	Sorry, there are errors in your submission. Please correct them.
	</div>
<% end %>



<%= label f, :title %>
<%= text_input f, :title %>
<%= error_tag f, :title %>

<%= label f, :description %>
<%= text_input f, :description %>
<%= error_tag f, :description %>

<%= label f, :ends_at, "Auction ends at" %>
<%= datetime_select f, :ends_at %>
<%= error_tag f, :ends_at %>
<div>
<%= submit "Submit" %>
</div>
<% end %>

apps/auction_web/lib/auction_web/templates/item/index.html.eex
<ul>
<%= for item <- @items do %>
<li>
<strong><%= link(item.title, to: Routes.item_path(@conn, :show, item)) %> </strong>: <%= item.description %>

</li>
<% end %>
</ul>

apps/auction_web/lib/auction_web/templates/item/new.html.eex
<h1> New Item</h1>

<%= render("form.html", item: @item, action: Routes.item_path(@conn, :create)) %>

apps/auction_web/lib/auction_web/templates/item/show.html.eex
<h1><%= @item.title %></h1>

<ul>
	<li><strong>Description:</strong> <%= @item.description %></li>
	<li><strong>Auction ends at:</strong> <%= @item.ends_at %></li>
	<li><strong>Creator</strong> <%= @owner %></li>
</ul>




<div style="display: flex; flex-direction: row;">
<%= if check_ends_at(@item.ends_at) do %>
<div style="flex: 1;">
		<h2>Bidding has expired</h2>

	</div>

<% else %>
	<div style="flex: 1;">
		<h2>Current Bids</h2>
		<div id="bids">
		<%= render_many @item.bids, AuctionWeb.BidView, "bid.html" %>
		</div>
	</div>
	<div style="flex: 1;">
		<%= if @current_user do %>
		<h2>Place your bid!</h2>
		<%= form_for @bid, Routes.item_bid_path(@conn, :create, @item), fn f -> %>
		<%= if @bid.action do %>
		<div class="alert alert-danger">
			Unfortunately, there are errors in your
			submission. Please correct them below.
		</div>
		<% end %>
		<div class="form-group">
			<%= label f, :amount, "Bid amount", class: "control-label" %>
			<%= error_tag f, :amount %>
			<%= number_input f, :amount, class: "form-control" %>
		</div>
		<%= submit "Submit", class: "btn btn-primary"%>
		<% end %>
		<% end %>
	</div>

<% end %>

</div>